DROP TABLE PET
DROP TABLE PET_OWNER
CREATE TABLE PET_OWNER (
  OwnerID        INT NOT NULL PRIMARY KEY,
  OwnerLastName  VARCHAR(50) NOT NULL,
  OwnerFirstName VARCHAR(50) NOT NULL,
  OwnerPhone     VARCHAR(12),
  OwnerEmail     VARCHAR(100) NOT NULL
)
CREATE TABLE PET(
  PetID INT IDENTITY PRIMARY KEY,
  PetName VARCHAR(50) NOT NULL,
  PetType VARCHAR(50) NOT NULL,
  PetBreed VARCHAR(30) NOT NULL REFERENCES BREED(Breed_Name),
  PetDOB DATE,
  PetWeight FLOAT NOT NULL,
  OwnerId INT NOT NULL,
  FOREIGN KEY (OwnerId) REFERENCES PET_OWNER(OwnerID)
)