CREATE TABLE PET(
  PetID INT IDENTITY PRIMARY KEY,
  PetName VARCHAR(50) NOT NULL,
  PetType VARCHAR(50) NOT NULL,
  PetBreed VARCHAR(50) NOT NULL,
  PetDOB DATE,
  PetWeight FLOAT NOT NULL,
  OwnerId INT NOT NULL,
  FOREIGN KEY (OwnerId) REFERENCES PET_OWNER(OwnerID)
)